config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

scope '/projects/:project_id/team_dashboard' do
  get '/', to: 'dashboard#index'
  post '/', to: 'dashboard#index'
  get 'edit_configuration/:id', to: 'dashboard#edit_configuration'
  get 'new_configuration', to: 'dashboard#new_configuration'
  post 'save_configuration', to: 'dashboard#save_configuration'
  get 'remove_configuration/:id', to: 'dashboard#remove_configuration'
  get 'load_configuration/:id', to: 'dashboard#load_configuration'

  get '/team_management', to: 'team_management#index'
  post 'team_management/update', to: 'team_management#update'

  resources :user_files, path: '/:file_kind', only: [:show, :destroy], param: 'user_id' do
    member do
      post 'create'
    end
  end
end

app/controllers/dashboard_controller.rb
require 'team_dashboard_constants'

class DashboardController < ApplicationController
  unloadable

  before_filter :find_project, only: %i[index edit_configuration new_configuration]
  before_filter :authorize, only: [:index]

  def index
    reset_session if request.get? && !params[:keep_session]
    save_to_session(params, request.post?)

    @technical_owner_field = CustomField.where(name: Setting.plugin_team_dashboard['technical_owner_field_name']).first
    @qa_owner_field = CustomField.where(name: Setting.plugin_team_dashboard['qa_owner_field_name']).first
    @pm_field = CustomField.where(name: TeamDashboardConstants::BELTECH_PM_FIELD_NAME).first
    @team_field = CustomField.where(name: Setting.plugin_team_dashboard['team_field_name']).first
    @external_priority_field = CustomField.where(name: TeamDashboardConstants::EXTERNAL_PRIORITY_FIELD_NAME).first

    @teams = TeamManagement.available_teams
    @selected_team = session_params(:team, @teams.keys.first)
    @selected_team_value = @teams[@selected_team]

    @versions = project_versions(@project)
    @selected_version_id = session_params(:target_version, current_version(@versions) && current_version(@versions).id)

    @ticket_status = 'open' if session_params(:ticket_status) == 'open'
    @show_support_tickets = params[:show_support_tickets] || session_params(:show_support_tickets)

    @show_ticket_different_teams = session_params(:show_ticket_different_teams, '1').to_i == 1

    @users = User.in_team(@selected_team_value).order([:firstname, :lastname])
    @configurations = TeamDashboardConfiguration.where(user_id: session[:user_id])

    @max_issues_count = @users.count > 0 ? @users.max_by { |user| user.overview_map_issues.count }.overview_map_issues.count : 0
  end

  def new_configuration
    @new_conf = true

    @teams = TeamManagement.available_teams
    @versions = ((@project.shared_versions.sort || []) + @project.rolled_up_versions.visible).uniq

    render 'edit_configuration'
  end

  def edit_configuration
    @new_conf = false
    @configuration = TeamDashboardConfiguration.find_by(id: params[:id])

    if TeamDashboardConfiguration.user_authorized?(@configuration, session[:user_id])
      @teams = TeamManagement.available_teams
      @versions = ((@project.shared_versions.sort || []) + @project.rolled_up_versions.visible).uniq
    else
      flash[:error] = l(:not_authorized_to_edit)
      redirect_to action: 'index'
    end
  end

  def load_configuration
    configuration = TeamDashboardConfiguration.find_by(id: params[:id])

    if TeamDashboardConfiguration.user_authorized?(configuration, session[:user_id])
      params[:keep_session] = true
      session[:team_dashboard_filter] ||= {}
      session[:team_dashboard_filter][:show_support_tickets] = false
      session[:team_dashboard_filter].merge!(configuration.params)
      flash[:notice] = l(:successfully_loaded)
    else
      flash[:error] = l(:not_authorized_to_load)
    end

    redirect_to action: 'index', keep_session: true
  end

  def save_configuration
    new_conf = params[:new_conf] == 'true'
    configuration = new_conf ? TeamDashboardConfiguration.new : TeamDashboardConfiguration.find_by(id: params[:configuration][:id])

    params[:configuration].delete(:id)
    params[:configuration][:user_id] = session[:user_id]

    if new_conf || TeamDashboardConfiguration.user_authorized?(configuration, session[:user_id])
      configuration_params[:params][:show_support_tickets] = true if configuration_params[:params][:show_support_tickets].present?
      configuration.update_attributes!(configuration_params)
      flash[:notice] = new_conf ? l(:successfully_created) : l(:successfully_updated)

      return redirect_to action: 'load_configuration', id: configuration.id if new_conf
    else
      flash[:error] = l(:not_authorized_to_update)
      return redirect_to action: 'index', keep_session: true
    end

    redirect_to action: 'index'
  end

  def remove_configuration
    configuration = TeamDashboardConfiguration.find_by(id: params[:id])

    if TeamDashboardConfiguration.user_authorized?(configuration, session[:user_id])
      configuration.destroy
      configurations = TeamDashboardConfiguration.user_configurations(session[:user_id])
      flash[:notice] = l(:successfully_removed)

      return redirect_to action: 'load_configuration', id: configurations.first.id if configurations.size == 1
    else
      flash[:error] = l(:not_authorized_to_remove)
    end

    redirect_to action: 'index'
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def project_versions(project)
    ((project.shared_versions.sort || []) + project.rolled_up_versions.visible).delete_if do |version|
      version.closed? || version.completed?
    end.uniq
  end

  def save_to_session(params_filter, force = false)
    session[:team_dashboard_filter] = params_filter if session && (force || !session[:team_dashboard_filter])
  end

  def reset_session
    session[:team_dashboard_filter] = nil
  end

  def session_params(name, default = nil)
    session.try(:[], :team_dashboard_filter).try(:[], name) || default
  end

  def configuration_params
    params.require(:configuration).permit(:configuration_name, :user_id).tap do |whitelisted|
      whitelisted[:params] = params[:configuration][:params]
    end
  end

  def current_version(versions)
    dates = {}
    versions.select do |version|
      version_date = version.name.match('\d+(-|\/)\d+(-|\/)\d+').to_s.gsub('-','/')
      next if version_date.blank?

      date = Date.strptime(version_date, '%Y/%m/%d') rescue nil || Date.strptime(version_date, '%m/%d/%Y') rescue nil
      dates[date] = version if date && (date >= Date.today)
    end
    dates.sort.first && dates.sort.first[1]
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def get_avatar(user)
    UserFile.fetch_user_file(user.id, UserFile::KIND_PHOTO) ?
      "team_dashboard/photo/#{user.id}" :
      "/plugin_assets/#{TeamDashboardConstants::PLUGIN_NAME}/images/avatars/user.png"
  end

  def avatar_path(user, assets_path)
    "avatars/#{user.photo_file_name(assets_path)}"
  end

  def eta_value(issue)
    remaining_hours = issue.remaining_hours

    ret_val = '--'
    ret_val = "#{remaining_hours.to_i}" + content_tag(:small, 'h') if remaining_hours && remaining_hours > 0
    ret_val.html_safe
  end

  def owner_value_short(user, issue)
    name = owner_value(user, issue).to_s.split(' ')

    ret_val = '--'
    ret_val = "#{name[0].first}#{name[1].first}" if name.length >= 2
    ret_val.html_safe
  end

  def owner_value(user, issue)
    user.is_qa_member?(@qa_owner_field) ? issue.qa_specialist_value : issue.technical_owner_value
  end

  def priority_class(issue)
    "priority width-15 #{issue.priority.name.downcase}-priority"
  end

  def tracker_class(issue)
    priority_class = 'fas ' + priority_class(issue)
    issue_tracker_name = issue.tracker.name

    icon = case issue_tracker_name
           when TeamDashboardConstants::TRACKERS[:bug] then ' fa-bug'
           when TeamDashboardConstants::TRACKERS[:feature] then ' fa-plus'
           when TeamDashboardConstants::TRACKERS[:user_story] then ' fa-address-card'
           when TeamDashboardConstants::TRACKERS[:spike] then ' fa-question-circle'
           else ' fa-circle'
           end

    priority_class + icon
  end

  def tracker_title(issue)
    "#{issue.tracker.name} (#{issue.priority.name} priority)"
  end

  def module_class
    issues_in_card = TeamDashboardConstants::ISSUES_PER_CARD
    issues_in_card_six = TeamDashboardConstants::ISSUES_PER_CARD_6

    return 'module' if @max_issues_count < issues_in_card
    (@max_issues_count >= issues_in_card && @max_issues_count < issues_in_card_six) ? 'module module-6' : 'module module-more'
  end

  def view_all_issues_path(user, issues)
    owner_field, search_params = detect_owner(issues, user)
    target_version = @selected_version_id ? "=&v[fixed_version_id][]=#{@selected_version_id}" : '*'

    params = []
    params << 'set_filter=1&sort=priority:desc,id&group_by=&t[]='
    params << "c[]=project&c[]=tracker&c[]=status&c[]=priority&c[]=subject&c[]=assigned_to&c[]=updated_on"
    params << "c[]=cf_#{owner_field.id}&c[]=fixed_version"
    params << "op[status_id]=*&op[cf_#{owner_field.id}]==&op[fixed_version_id]=#{target_version}"
    params << "f[]=status_id&f[]=cf_#{owner_field.id}&f[]=fixed_version_id&f[]="
    params << "f[]=cf_#{@team_field.id}&op[cf_#{@team_field.id}]==&v[cf_#{@team_field.id}][]=#{@selected_team_value}" unless @show_ticket_different_teams
    params << "c[]=story_points&c[]=cf_#{@external_priority_field.id}"
    params << "utf8=✓&v[cf_#{owner_field.id}][]=#{search_params}"
    URI.escape("/projects/plansource/issues?#{params.join('&')}")
  end

  def issue_id_and_subject_tag(user, issue, display_shared_mark, display_initials)
    hint = css = link_css = nil

    team_css = 'team'
    issue_team = issue.team_value
    if issue_team.blank?
      team_css = "#{team_css} undefined"
      issue_team = 'not assigned'
    end

    options = {}
    options = options.merge(class: css.strip) unless css.blank?
    options = options.merge(title: hint.strip) unless hint.blank?

    ret_val = ''
    ret_val << content_tag(:span, 'S-', options) if display_shared_mark && issue.is_shared_with?(user)
    ret_val << content_tag(:span, issue.id, options)
    ret_val << content_tag(:span, issue_team, class: team_css) if @show_ticket_different_teams
    ret_val << "\n"
    ret_val << link_to(issue.subject, issue_path(issue), title: issue.subject, class: link_css)
    ret_val.html_safe
  end

  def version_options_for_select(versions, selected_version_id=nil, show_completed = false)
    completed_versions = versions.select {|version| version.closed? || version.completed? }
    worked_versions = versions - completed_versions

    selected_version_id = worked_versions.first.try(:id) || completed_versions.first.try(:id) unless selected_version_id

    if show_completed && completed_versions
      grouped = [
        ['', worked_versions.collect {|version| [version.name, version.id]}],
        ['Completed Versions', completed_versions.collect {|version| [version.name, version.id]}]
      ]
      grouped_options_for_select(grouped, selected_version_id)
    else
      options_from_collection_for_select(worked_versions, :id, :name, selected_version_id)
    end
  end

  def team_points()
    users_id = @users.collect { |u| u.id }
    users_names = @users.collect { |u| u.name }

    issues =
      Issue.select('distinct issues.*, ad.story_points, cv.value AS `external_priority`').visible
        .joins("JOIN custom_values cf ON cf.customized_id = issues.id AND customized_type = 'Issue'")
        .joins('LEFT JOIN custom_fields as ft on cf.custom_field_id = ft.id')
        .joins("JOIN custom_fields cuf ON cuf.name = '#{TeamDashboardConstants::EXTERNAL_PRIORITY_FIELD_NAME}'")
        .joins('LEFT JOIN custom_values cv ON cv.customized_id = issues.id AND cv.custom_field_id = cuf.id AND cv.customized_type = "Issue"')
        .joins('LEFT JOIN agile_data ad ON ad.issue_id = issues.id')
        .where(fixed_version_id: @selected_version_id)
        .where('(cf.custom_field_id = :qa_field_id AND IF (ft.field_format = "user", cf.value IN (:users_id),  cf.value IN (:users_name) ))'\
          'OR (cf.custom_field_id = :technical_field_id AND IF (ft.field_format = "user", cf.value IN (:users_id),  cf.value IN (:users_name) ))'\
          'OR (cf.custom_field_id = :pm_field_id AND IF (ft.field_format = "user", cf.value IN (:users_id),  cf.value IN (:users_name) ))',
          {
            qa_field_id: @qa_owner_field ? @qa_owner_field.id : '',
            technical_field_id: @technical_owner_field.id,
            pm_field_id: pm_field_instance.id,
            users_name: users_names,
            users_id: users_id
          }
        )

    issues = issues.joins("JOIN custom_fields cf_t ON cf_t.id = '#{@team_field.id}'")
                 .joins("JOIN custom_values cv_t ON cv_t.customized_id = issues.id
                                                  AND cv_t.custom_field_id = cf_t.id
                                                  AND cv_t.value = '#{@selected_team_value}'")

    sums = Issue.from(@ticket_status ? issues.open : issues, :a)
             .pluck('sum(a.story_points) as sp', 'sum(a.external_priority ) as ep').first
    sums = sums.collect { |v| v.to_i}

    { external_proirity: sums[1], story_points: sums[0] }
  end

  def user_issues(user)
    owner_field = owner_instance(user)
    value = owner_field.field_format == 'user' ? user.id : user.name

    issues =
      Issue.select('issues.*, ad.story_points, cv.value AS `external_priority`').visible
        .joins("JOIN custom_values cf ON cf.customized_id = issues.id AND customized_type = 'Issue'")
        .joins("JOIN custom_fields cuf ON cuf.name = '#{TeamDashboardConstants::EXTERNAL_PRIORITY_FIELD_NAME}'")
        .joins('LEFT JOIN custom_values cv ON cv.customized_id = issues.id AND cv.custom_field_id = cuf.id AND cv.customized_type = "Issue"')
        .joins('LEFT JOIN agile_data ad ON ad.issue_id = issues.id')
        .where(fixed_version_id: @selected_version_id)
        .where('(cf.custom_field_id = ? AND cf.value = ?) OR (cf.custom_field_id = ? AND `cf`.value = ?)', owner_field.id, value, pm_field_instance.id, user.name)
        .order('issues.priority_id DESC')

    unless @show_ticket_different_teams
      issues = issues.joins("JOIN custom_fields cf_t ON cf_t.id = '#{@team_field.id}'")
                     .joins("JOIN custom_values cv_t ON cv_t.customized_id = issues.id
                                                    AND cv_t.custom_field_id = cf_t.id
                                                    AND cv_t.value = '#{@selected_team_value}'")
    end

    @ticket_status ? issues.open : issues
  end

  def support_issues
    all_issues =
      Issue.select('cv1.value as esc_tier_3_time, cv2.value as support_analyst, issues.*')
        .joins('join issue_statuses iss_st on iss_st.id = issues.status_id and iss_st.is_closed != 1')
        .joins("join custom_values cv1 on cv1.customized_id = issues.id and cv1.customized_type = 'Issue'")
        .joins("join custom_fields cf1 on cf1.id = cv1.custom_field_id and cf1.name = '#{TeamDashboardConstants::TIER_3_ESC_DATE_FIELD_NAME}'")
        .joins("join custom_values cv2 on cv2.customized_id = issues.id and cv2.customized_type = 'Issue'")
        .joins("join custom_fields cf2 on cf2.id = cv2.custom_field_id and cf2.name = '#{TeamDashboardConstants::SUPPORT_ANALYST_FIELD_NAME}'")
        .joins("join custom_values cv3 on cv3.customized_id = issues.id and cv3.customized_type = 'Issue'")
        .joins("join custom_fields cf3 on cf3.id = cv3.custom_field_id and cf3.name = '#{TeamDashboardConstants::TIER_3_TEAM_FIELD_NAME}'")
        .where("cv1.value != '' and cv3.value = ?", @teams[@selected_team])
        .order('issues.priority_id DESC')

    issues = {}
    selected_issue_ids = []

    TeamDashboardConstants::SUPPORT_TICKET_GROUPS.each do |group_code, _|
      case group_code
      when :support_team then
        issues[group_code] =
          all_issues
            .select("CONCAT(u.firstname, ' ', u.lastname) as assigned_to")
            .joins('JOIN users u on u.id = issues.assigned_to_id')
            .where("cv2.value != ''")
            .having("INSTR((select cf.possible_values from custom_fields cf
                    where cf.name = 'Support Analyst'), assigned_to)")
        selected_issue_ids.push(issues[group_code].map(&:id)).flatten!
      when :ps_developer then
        issues[group_code] =
          all_issues
            .joins('join users u on u.id = issues.assigned_to_id')

app/views/dashboard/_avatar.html.erb
<%= tag(:img, src: get_avatar(user), id: "avatar_#{user.id}", class: 'avatar', title: "#{user.name}", size: '60x60', onclick: "sendAvatar(#{user.id})") %>

app/views/dashboard/_form.html.erb
<% config_params = configuration.try(:params) || {} %>

<div class="box">
  <div class="tabular">
    <%= hidden_field_tag 'configuration[id]', configuration.try(:id) %>
    <%= hidden_field_tag 'new_conf', new_conf %>

    <p>
      <label for='configuration_configuration_name'><%= l(:label_configuration_name) %></label>
      <%= text_field_tag 'configuration[configuration_name]', configuration.try(:configuration_name), size: 40, maxlength: 80, required: true, placeholder: 'Enter configuration name...' %>
    </p>

    <p>
      <label for='configuration_params_show_support_tickets'><%= l(:label_show_support_tickets) %></label>
      <%= check_box_tag 'configuration[params[show_support_tickets]]', config_params[:show_support_tickets], config_params[:show_support_tickets], onchange: 'disableFields(this);' %>
    </p>

    <p>
      <label for='configuration_params_show_ticket_all_teams'><%= l(:label_ticket_for_different_teams) %></label>
      <%= hidden_field_tag 'configuration[params[show_ticket_different_teams]]', 0 %>
      <%= check_box_tag 'configuration[params[show_ticket_different_teams]]', 1, config_params[:show_ticket_different_teams], disabled: config_params[:show_support_tickets] %>
    </p>

    <p>
      <label for='configuration_params_team'><%= l(:label_team) %></label>
      <%= select_tag 'configuration[params[team]]', options_for_select(@teams.invert.to_a, config_params[:team]), required: true %>
    </p>

    <p class="support_disabled" <%= 'style="opacity: 0.6;"'.html_safe if config_params[:show_support_tickets] %>>
      <label for='configuration_params_target_version'><%= l(:label_target_version) %></label>
      <%= select_tag 'configuration[params[target_version]]', version_options_for_select(@versions, config_params[:target_version]), disabled: config_params[:show_support_tickets] %>
    </p>

    <p class="support_disabled" <%= 'style="opacity: 0.6;"'.html_safe if config_params[:show_support_tickets] %>>
      <label for='configuration_params_ticket_status'><%= l(:label_ticket_status) %></label>
      <%= select_tag 'configuration[params[ticket_status]]', options_for_select([['All', :all], ['Open', :open]], config_params[:ticket_status]), disabled: config_params[:show_support_tickets] %>
    </p>
  </div>
</div>

app/views/dashboard/_grid.html.erb
<% if users.count > 0 %>
  <%= content_tag(:h3, title) if title.present? %>
  <div class="grid grid-border">
    <% users.each do |user| %>
      <div class="col-1-2">
        <div class="<%= module_class %>">
          <div class="grid">
            <div class="col-avatar">
              <%= render partial: 'avatar', locals: { user: user } %>
            </div>
            <div class="col-desc">
              <table class="user-issues" cellpadding="0" cellspacing="0">
                <% issues = user_issues(user) %>
                <tr>
                  <td class="user-name">
                    <strong><%= link_to user.name, user_path(user) %></strong><span class="shaded-font" style="margin-left: 5px"><%= user_positions(user) %></span>
                    <span class="shaded-font story-points points" title='External Points'>EP: <%= external_points(issues) %></span>
                  </td>
                  <td class="shaded-font story-points" title='Story Points' nowrap>SP: <%= story_points(issues) %></td>
                </tr>
                <% issues.each_with_index do |issue, index| %>
                  <tr>
                    <% if index + 1 < TeamDashboardConstants::ISSUES_PER_CARD_6 || issues.to_a.count == TeamDashboardConstants::ISSUES_PER_CARD_6 %>
                      <td>
                        <p class="truncate <%= ticket_team_css(issue) %>">
                          <%= content_tag(:i, '', class: tracker_class(issue), title: tracker_title(issue)) if display_priority %>
                          <%= issue_id_and_subject_tag user, issue, display_shared_mark, display_initials %>
                        </p>
                      </td>
                        <%= points_content_tag(issue, :td, class: 'initials shaded-font') %>
                    <% else %>
                      <td class="more">
                        <%title = "View all issues where #{user.name} is #{owner_instance(user).name}"%>
                        <%= link_to l(:label_issue_view_all), view_all_issues_path(user, issues), title: title%>
                      </td>
                      <% break %>
                    <% end %>
                  </tr>
                <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
    <% end %>

    <% if users.count.odd? %>
      <div class="col-1-2">
        <div class="<%= module_class %>"></div>
      </div>
    <% end %>
  </div>

  <div id="avatar_popup" style="display: none;">
    <form id="pictureForm">
      <p style="text-align: center"><input type="file" id="pictureInput" accept="image/jpeg, image/png" ></p>
    </form>
    <a id="clear_image" href="#" class="clear_image" title="Clear Image" onclick="clearImage()"></a>
    <input type="hidden" id="hidden_input" value="">
    <div id="target" class="uploadImage"></div>
  </div>
<% end %>

app/views/dashboard/_issue_card.html.erb
<div class="issue-card <%= get_color_class(issue) %> " data-id="<%= issue.id %>">
  <span class="fields">
    <p class="issue-id">
      <strong><%= h("#{issue.tracker} ##{issue.id}") %></strong>
    </p>
    <p class="name" ><%= link_to "#{issue.subject.truncate(100)}", issue_path(issue) %></p>
    <p class="issue_attributes">
      <% get_issue_attributes(issue).each do |attribute| %>
        <b><%= attribute[:caption] %></b>: <%= attribute[:value] %><br>
      <% end %>
    </p>
  </span>
</div>

app/views/dashboard/_sidebar.html.erb
<%= form_tag({}) do %>
  <div class="filter-block">
    <h3><%= l(:label_team_management)%></h3>

    <ul>
      <li><%= link_to l(:label_edit_teams), team_management_path %></li>
    </ul>

    <h3><%= l(:label_filter)%></h3>

    <ul>
      <li>
        <label for='show_support_tickets'><%= l(:label_show_support_tickets) %></label>
        <%= check_box_tag 'show_support_tickets', @show_support_tickets, @show_support_tickets, onchange: 'disableFields(this);' %>
      </li>
      <li class="support_disabled" <%= 'style="opacity: 0.6;"'.html_safe if @show_support_tickets %>>
        <label for='show_ticket_all_teams'><%= l(:label_ticket_for_different_teams) %></label>
        <%= hidden_field_tag 'show_ticket_different_teams', 0 %>
        <%= check_box_tag 'show_ticket_different_teams', 1, @show_ticket_different_teams, disabled: @show_support_tickets %>
      </li>
      <li>
        <label for='team'><%= l(:label_team) %></label><br />
        <%= select_tag 'team', options_for_select(@teams.invert.to_a, @selected_team) %>
      </li>
      <% if false && @technical_owners.present? %>
        <li>
          <label for='technical_owner'><%= l(:label_technical_owner) %></label><br />
          <%= select_tag 'technical_owner', options_for_select(@technical_owners, @selected_technical_owner) %>
        </li>
      <% end %>
      <li class="support_disabled" <%= 'style="opacity: 0.6;"'.html_safe if @show_support_tickets %>>
        <label for='target_version'><%= l(:label_target_version) %></label><br />
        <%= select_tag 'target_version', version_options_for_select(@versions, @selected_version_id), disabled: @show_support_tickets %>
      </li>
      <li class="support_disabled" <%= 'style="opacity: 0.6;"'.html_safe if @show_support_tickets %>>
        <label for='ticket_status'><%= l(:label_ticket_status) %></label><br />
        <%= select_tag 'ticket_status', options_for_select([['All', :all], ['Open', :open]], @ticket_status), disabled: @show_support_tickets %>
      </li>
    </ul>

    <p>
      <%= submit_tag l(:button_apply) %>
    </p>

    <% if @configurations.any? %>
      <h3><%= l(:label_saved_configuration)%></h3>
    <% end %>

    <ul id="saved_configuration">
      <% @configurations.each do |configuration| %>
        <li>
          <span><%= link_to '', url_for(controller: 'dashboard', action: 'edit_configuration', id: configuration.id), class: 'icon icon-edit', title: l(:label_button_edit) %></span>
          <span><%= link_to '', url_for(controller: 'dashboard', action: 'remove_configuration', id: configuration.id), class: 'icon icon-del', title: l(:label_button_delete), data: { confirm: 'Are you sure?' } %></span>
          <span><%= link_to truncate(configuration.configuration_name, length: 40), url_for(controller: 'dashboard', action: 'load_configuration', id: configuration.id), title: configuration.configuration_name, style: 'display: inline-block' %></span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/dashboard/_support_tickets.html.erb
<div>
  <table class="list issues-board">
    <thead>
    <tr>
      <% TeamDashboardConstants::SUPPORT_TICKET_GROUPS.each do |_, group_value| %>
        <th><%= group_value %></th>
      <% end %>
    </tr>
    </thead>
    <tr style="text-align: center;white-space: nowrap;" class="issue">
      <% support_issues.each do |_, issues_data| %>
        <td class="issue-status-col">
        <% issues_data.each do |issue| %>
          <%= render partial: 'issue_card', locals: { issue: issue } %>
        <% end if issues_data %>
        </td>
      <% end %>
    </tr>
  </table>
</div>

app/views/dashboard/edit_configuration.html.erb
<% html_title @new_conf ? l(:label_button_new) : l(:label_edit_configuration) %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'team_dashboard', plugin: 'team_dashboard' %>
  <%= javascript_include_tag 'team_dashboard', plugin: 'team_dashboard' %>
<% end %>

<h2><%= @new_conf ? l(:label_button_new) : l(:label_edit_configuration) %></h2>

<%= form_tag(url_for(controller: 'dashboard', action: 'save_configuration'), id: "configuration-form") do %>
  <%= render partial: 'form', locals: { configuration: @configuration, new_conf: @new_conf } %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/dashboard/index.html.erb
<% html_title l(:label_team_dashboard) %>

<div id="dashboard_header">
  <div class="label_text">
    <h2><%= l(:label_team_dashboard) %></h2>
  </div>

  <div class="new_link">
    <%= link_to l(:label_button_new), url_for(controller: 'dashboard', action: 'new_configuration'), class: 'icon icon-add', title: l(:label_button_new) %>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render partial: 'sidebar' %>
<% end %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'team_dashboard', plugin: 'team_dashboard' %>
  <%= stylesheet_link_tag 'font-awesome/css/fontawesome-all', plugin: 'team_dashboard' %>
  <%= javascript_include_tag 'team_dashboard', plugin: 'team_dashboard' %>
<% end %>

<% tpoints = team_points %>
<table class="user-issues team_points" style="" cellpadding="0" cellspacing="0">
  <tbody>
  <tr>
    <td>Team External Priority Points</td>
    <%= content_tag(:td, tpoints[:external_proirity], class: 'initials shaded-font')%>
  </tr>
  <tr>
    <td>Team Story Points</td>
    <%= content_tag(:td, tpoints[:story_points], class: 'initials shaded-font')%>
  </tr>
  <tr>
    <td>Total Team Points</td>
    <%= content_tag(:td, tpoints[:external_proirity]+tpoints[:story_points], class: 'initials shaded-font')%>
  </tr>
  </tbody>
</table>

<div class="grid">
  <div class="col-1-1">
    <% if @show_support_tickets %>
      <%= render partial: 'support_tickets' %>
    <% else %>
      <%= render partial: 'grid', locals: {
          users: @users,
          title: '',
          display_priority: true,
          display_shared_mark: true,
          display_eta: true,
          display_initials: true
      } %>
    <% end %>
  </div>
</div>

<script>
    $(document).ready(truncateIssuesNames);
    $(window).resize(truncateIssuesNames);
</script>