config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

scope '/projects/:project_id/team_dashboard' do
  get '/', to: 'dashboard#index'
  post '/', to: 'dashboard#index'
  get 'edit_configuration/:id', to: 'dashboard#edit_configuration'
  get 'new_configuration', to: 'dashboard#new_configuration'
  post 'save_configuration', to: 'dashboard#save_configuration'
  get 'remove_configuration/:id', to: 'dashboard#remove_configuration'
  get 'load_configuration/:id', to: 'dashboard#load_configuration'

  get '/team_management', to: 'team_management#index'
  post 'team_management/update', to: 'team_management#update'

  resources :user_files, path: '/:file_kind', only: [:show, :destroy], param: 'user_id' do
    member do
      post 'create'
    end
  end
end

app/models/team_management.rb
class TeamManagement < ActiveRecord::Base
  unloadable

  belongs_to :user

  validates_presence_of :team_name
  validates_presence_of :user_id

  def self.team_members
    ret_val = {}
    self.all.each do |assignment|
      team_key = assignment.team_name.parameterize
      ret_val[team_key] ||= []
      ret_val[team_key] << assignment.user
    end
    ret_val
  end

  def self.available_teams
    team_field = CustomField.where(name: Setting.plugin_team_dashboard['team_field_name']).first
    teams = team_field.present? ? team_field.possible_values_options : []

    ret_val = {}
    teams.each { |team| ret_val[team.parameterize] = team }
    ret_val
  end

  def self.all_users
    User.sorted.where(type: TeamDashboardConstants::USER_TYPE_NAME).to_a
  end

  def self.teamed_users
    self.all.collect { |team| team.user }
  end

  def self.non_teamed_users
    self.all_users - self.teamed_users
  end

  def self.team(name)
    self.where(team_name: name)
  end
end

app/controllers/team_management_controller.rb
require 'team_dashboard_constants'

class TeamManagementController < ApplicationController

  before_filter :find_project, :initialize_for_layout, :authorize, only: [:index, :update]


  def initialize_for_layout
    @teams_available = TeamManagement.available_teams
  end

  def index
    team_members = TeamManagement.team_members
    @teams = {}
    @teams_available.each_key { |team_key| @teams[team_key] = team_members[team_key] || [] }
    @unselected_users = TeamManagement.all_users
  end

  def update
    TeamManagement.delete_all

    option_keys = params.keys.select { |pm| pm['team_'] }
    option_keys.each do |param|
      team = params[param]
      team.each do |user|
        team_name = @teams_available[param[5..-1]]
        user_id = user.to_i
        TeamManagement.create!(team_name: team_name, user_id: user_id) if user_id.to_i > 0 && team_name.present?
      end if team.is_a?(Array) && team.any?
    end

    flash[:notice] = 'Groups updated successfully.'
    redirect_to_referer_or action: 'index', project_id: params[:project_id]
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end
end

app/views/team_management/index.html.erb
<% html_title 'Team Management' %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'team_dashboard', plugin: 'team_dashboard' %>
  <%= javascript_include_tag 'team_dashboard', plugin: 'team_dashboard' %>
<% end %>

<div class='wiki wiki-page'>
  <h1>Teams Management</h1>
</div>

<%= form_tag(@project ? team_management_update_path(@project) : team_management_update_path, onsubmit: 'make_selects_send_to_server()') do %>
  <table class="query-columns">
    <% @teams.each_with_index  do |(team_key, users), index| %>
        <% team_control_id = "team_#{team_key}" %>
        <td>
          <td style="padding-left:0">
            <%= label_tag team_control_id, "#{@teams_available[team_key]}" %>
            <br />
            <%= select_tag "team_#{team_key}",
                           options_for_select(users.map { |u| [u.name, u.id] } || []),
                           id: team_control_id, multiple: true, size: 10, style: 'width:250px' %>
          </td>
          <td class="buttons">
            <input type="button" value="&#8594;" onclick="removeFromTeam('#<%= "#{team_control_id}" %>');" />
            <br />
            <input type="button" value="&#8592;" onclick="addToTeam('#available_users', '#<%= "#{team_control_id}" %>');" />
          </td>
          <% if index == 0 %>
            <td rowspan="<%= @teams.count %>">
              <%= label_tag 'available_users', 'Available Users' %>
              <br />
              <%= select_tag 'available_users',
                             options_for_select(@unselected_users.map { |u| [u.name, u.id] } || []),
                             id: 'available_users', multiple: true, size: (12 * @teams.count), style: 'width:250px' %>
            </td>
          <% end %>
        </tr>
    <% end %>
  </table>
  <%= submit_tag l(:button_save) %>
  <%= link_to 'Back', controller: 'dashboard', action: 'index', project_id: params[:project_id] %>
<% end %>

<script>
    function make_selects_send_to_server() {
      $("select[name^='team_'] option").prop('selected', true);
      return false;
    }
</script>